In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(a.shape) #returns a tuple that shows the size of array/matrix
print(a.dtype) #shows the ytpe of data
print(a.ndim) #shows the dimension of array
print(a.size) #shows total number of elements
print(a.itemsize) #shows the size of item in bytes

(4,)
int32
1
4
4


In [4]:
a[2]

3

In [5]:
a[3]=10
print(a)

[ 1  2  3 10]


In [6]:
a[3] = 4
b = np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [7]:
dot_product = np.dot(a,b)
dot_product

70

In [8]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
b = a[0,1:3]
print(b)

[2]


In [10]:
b = a[:1,0]
print(b)

[1]


In [11]:
b = a[-1,-2]
print(b)

5


In [12]:
bool_index = a>2
print(bool_index)

[[False False]
 [ True  True]
 [ True  True]]


In [13]:
print(a[bool_index])

[3 4 5 6]


In [14]:
print(a[a>2])

[3 4 5 6]


In [15]:
b = np.where(a>2, a, 0)
print(b)

[[0 0]
 [3 4]
 [5 6]]


In [16]:
a = np.array([10, 25, 89, 90, 46, 78, 94, 103])
b = [1, 3, 5]
print(a[b])

[25 90 78]


In [17]:
even = np.argwhere(a%2==0).flatten()
print(even)
print(a[even])

[0 3 4 5 6]
[10 90 46 78 94]


In [18]:
a = np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [19]:
b = a.reshape((2,3))
print(b)

[[1 2 3]
 [4 5 6]]


In [20]:
b = a[np.newaxis,:]
print(b)

[[1 2 3 4 5 6]]


In [21]:
print(b.shape)

(1, 6)


In [22]:
b = a[:, np.newaxis]
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [33]:
a = np.array([[1,2], [3,4]])
print(a)
b = np.array([[5,6]])
print(b)
c = np.concatenate((a,b.T), axis = 1) #Axis is 0 by default
print(c)

[[1 2]
 [3 4]]
[[5 6]]
[[1 2 5]
 [3 4 6]]


In [37]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c1 = np.hstack((a,b))
print(c1)
c2 = np.vstack((a,b))
print(c2)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [38]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([1,0,1])
print(x+y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [41]:
a = np.array([[7,8,9,10,11,12,13], [14,15,16,17,18,19,20]])
print(a.sum(axis=1)) #axis is none as default

[ 70 119]


In [47]:
print(a.std(axis=None))
print(a.var(axis=None))
print(a.mean(axis=None))
print(a.max(axis=None))
print(a.min(axis=None))

4.031128874149275
16.25
13.5
20
7


In [50]:
a = np.array([1,2,3])
b = a
b[0] = 64
print(b)
print(a)

[64  2  3]
[64  2  3]


In [51]:
b = a.copy()
b[0] = 75
print(b)
print(a)

[75  2  3]
[64  2  3]


In [53]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [55]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
a = np.full((2,3), 5)
print(a)

[[5 5 5]
 [5 5 5]]


In [60]:
a = np.linspace(0,10,5) #start vayle, stop value, no. of elements. The elements are equally spaced
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [62]:
a = np.random.random((3,3)) #betweee 0&1
print(a)

[[0.71191744 0.09647747 0.91538725]
 [0.8951604  0.25699751 0.87543986]
 [0.33278591 0.2183138  0.94053253]]


In [66]:
a = np.random.rand(3,3)
print(a)

[[0.51805135 0.61122594 0.56296388]
 [0.6854083  0.46806095 0.01853101]
 [0.62826966 0.22936776 0.00962624]]


In [70]:
a = np.random.randint(3,10,size=(3,3)) #between 3&10. If only one number given then starts from 0
print(a)

[[8 5 9]
 [8 5 5]
 [5 8 9]]
